DATA:
  BATCH_SIZE: 32
  IMG_SIZE:
  - 240
  - 384
  ORI_SMOOTH_FACTOR: 3
  POS_SMOOTH_FACTOR: 100
  OTHER_AUGMENT: true
  PATH: ../datasets/speed
  ROT_AUGMENT: true
  SHUFFLE: true
MODEL:
  BACKBONE:
    NAME: mobilenet_v2_brevitas
    RESIDUAL: true
  HEAD:
    NAME: ursonet_brevitas
    ORI: classification
    N_ORI_BINS_PER_DIM: 12
    ORI_DELETE_UNUSED_BINS: False
    POS: regression
    N_POS_BINS_PER_DIM: 10
    KEYPOINTS_PATH: models/3d_models/tangoPoints.mat
  MANUAL_COPY: true
  PRETRAINED_PATH: models/mursop_fp32_speed/model/parameters.pt
  QUANTIZATION: true
TRAIN:
  DECAY: 0.0
  GAMMA: 0.1
  LR: 0.01
  MILESTONES:
  - 7
  - 15
  MOMENTUM: 0.9
  N_EPOCH: 20
  OPTIM: SGD
  SCHEDULER: MultiStepLR
  CLIP_BATCHNORM: True